# Exercises

1. Make an all-ones array shape (5, 5):

In [1]:
# please write your code here:
import numpy as np

a = np.ones((5, 5)) # 5 rows 5 columns
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

2. Write a NumPy program to creat two 2D arrays and implement the addition between two arrays:

In [8]:
# please write your code here:
b = np.array([[3, 1, 2], [3, 2, 1]]) # 2 rows 3 columns
c = np.array([[5, 8, 2,], [9, 3, 2]])

print(b + c)

[[ 8  9  4]
 [12  5  3]]


3. Creat a 2D array and generate a new array containing its 2nd and 3rd rows.

In [15]:
# please write your code here:
d = np.array([[3, 2, 1], [1, 2, 3], [2, 1, 3]])
d1 = np.array([d[1, :], d[2, :]])

# OR: 
d2 = d[1:3, :]
d2

array([[1, 2, 3],
       [2, 1, 3]])

4. Creat two 2D arrays and do multiplication of two arrays.Please try to use [**.multiply()**](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html) .

In [14]:
# please write your code here:
e = np.multiply(b, c)
e

array([[15,  8,  4],
       [27,  6,  2]])